### ISSUE TITLE
Setup a pages.dev CD

### ISSUE THREAD

**Issue by ujjwal-kr** [hackarmour/ha-landing-page#2]
A temporary cloudflare pages continuous deployment system should be setup (like creating a deployment for each PR) to make review process simpler

CC @itsmebirdie

**Comment by itsmebirdie** [comment]
Already assigned to @0xGamer

**Comment by itsmebirdie** [comment]
Successfully set up CD using pages.dev at [ha-landing-page.pages.dev](https://ha-landing-page.pages.dev)

<details>
<summary>Initial Build Log</summary>
<br>
<pre>
10:25:39.310	Initializing build environment. This may take up to a few minutes to complete
10:28:10.064	Success: Finished initializing build environment
10:28:10.064	Cloning repository...
10:28:11.762	Success: Finished cloning repository files
10:28:12.474	Installing dependencies
10:28:12.476	Python version set to 2.7
10:28:13.302	v12.18.0 is already installed.
10:28:13.727	Now using node v12.18.0 (npm v6.14.4)
10:28:13.762	Started restoring cached build plugins
10:28:13.766	Finished restoring cached build plugins
10:28:13.868	Attempting ruby version 2.7.1, read from environment
10:28:14.734	Using ruby version 2.7.1
10:28:14.965	Using PHP version 5.6
10:28:14.990	5.2 is already installed.
10:28:14.994	Using Swift version 5.2
10:28:14.995	Started restoring cached node modules
10:28:14.997	Finished restoring cached node modules
10:28:15.147	Installing NPM modules using NPM version 6.14.4
10:28:15.735	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
10:28:21.960	
10:28:21.960	> core-js-pure@3.15.2 postinstall /opt/buildhome/repo/node_modules/core-js-pure
10:28:21.960	> node -e "try{require('./postinstall')}catch(e){}"
10:28:21.960	
10:28:22.013	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
10:28:22.013	
10:28:22.013	[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
10:28:22.013	[96m>[94m https://opencollective.com/core-js [0m
10:28:22.013	[96m>[94m https://www.patreon.com/zloirock [0m
10:28:22.013	
10:28:22.013	[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
10:28:22.013	
10:28:22.312	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
10:28:22.312	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:28:22.313	
10:28:22.315	added 486 packages from 319 contributors and audited 487 packages in 6.615s
10:28:22.457	
10:28:22.457	78 packages are looking for funding
10:28:22.457	  run `npm fund` for details
10:28:22.457	
10:28:22.458	found 0 vulnerabilities
10:28:22.458	
10:28:22.472	NPM modules installed
10:28:22.675	Installing Hugo 0.54.0
10:28:23.117	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
10:28:23.118	Started restoring cached go cache
10:28:23.122	Finished restoring cached go cache
10:28:23.144	go version go1.14.4 linux/amd64
10:28:23.148	go version go1.14.4 linux/amd64
10:28:23.149	Installing missing commands
10:28:23.149	Verify run directory
10:28:23.149	Executing user command: next build && next export
10:28:23.826	info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
10:28:23.953	warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
10:28:23.968	Attention: Next.js now collects completely anonymous telemetry regarding usage.
10:28:23.968	This information is used to shape Next.js' roadmap and prioritize features.
10:28:23.968	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
10:28:23.968	https://nextjs.org/telemetry
10:28:23.968	
10:28:24.002	info  - Checking validity of types...
10:28:25.328	info  - Creating an optimized production build...
10:28:33.733	info  - Compiled successfully
10:28:33.733	info  - Collecting page data...
10:28:33.860	info  - Generating static pages (0/3)
10:28:34.011	info  - Generating static pages (3/3)
10:28:34.012	info  - Finalizing page optimization...
10:28:34.014	
10:28:34.020	Page                                Size     First Load JS
10:28:34.020	┌ ○ /                               2.91 kB        66.5 kB
10:28:34.020	├   └ css/b137277879c961731dcf.css  189 B
10:28:34.020	├   /_app                           0 B            63.6 kB
10:28:34.020	└ ○ /404                            3.17 kB        66.8 kB
10:28:34.020	+ First Load JS shared by all       63.6 kB
10:28:34.020	  ├ chunks/framework.64eb71.js      42 kB
10:28:34.020	  ├ chunks/main.1f18f7.js           20.2 kB
10:28:34.020	  ├ chunks/pages/_app.11bd90.js     555 B
10:28:34.020	  ├ chunks/webpack.61095c.js        810 B
10:28:34.020	  └ css/96d85f85770d1701743e.css    213 B
10:28:34.020	
10:28:34.022	λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
10:28:34.022	○  (Static)  automatically rendered as static HTML (uses no initial props)
10:28:34.022	●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
10:28:34.022	   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
10:28:34.022	
10:28:34.522	info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
10:28:34.848	info  - using build directory: /opt/buildhome/repo/.next
10:28:34.851	info  - Copying "static build" directory
10:28:34.854	info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
10:28:34.855	info  - Launching 1 workers
10:28:34.855	info  - Exporting (0/2)
10:28:34.856	info  - Copying "public" directory
10:28:34.986	info  - Exporting (2/2)
10:28:34.987	Export successful. Files written to /opt/buildhome/repo/out
10:28:35.003	Finished
10:28:35.003	Validating asset output directory
10:28:35.988	Deploying your site to Cloudflare's global network...
10:28:41.447	Success: Your site was deployed!
</pre>
</details>
